# Generated by Django 2.2 on 2020-08-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prod',
            new_name='Product',
        ),
    ]
